version: '2'
services:
  mysqlmaster:
    build: .
    environment:
#      - "MYSQL_ROOT_PASSWORD=aTestPwd"
#      - "MYSQL_REPLICATION_USER=rpl_user"
#      - "MYSQL_REPLICATION_PASSWORD=rpl_pass"
      - character-set-server=utf8
      - collation-server=utf8_general_ci
#    networks:
#       - cluster1
    volumes:
      - ./data/mysql-master:/var/lib/mysql/
      - ./config/mysql-master:/etc/mysql/conf.d/
    command: /entrypoint.sh --group_replication_bootstrap_group=ON
#     entrypoint:
#        - /entrypoint.sh
#        - --group_replication_bootstrap_group=ON
  mysqlslave:
     build: .
    environment:
#      - "MYSQL_ROOT_PASSWORD=root"
      - character-set-server=utf8
      - collation-server=utf8_general_ci
#    networks:
#       - cluster1
    volumes:
      - ./data/mysql-slave:/var/lib/mysql/
      - ./config/mysql-slave:/etc/mysql/conf.d/
    command: /entrypoint.sh --group_replication_group_seeds='mysqlmaster:6606'
#     entrypoint:
#        - /entrypoint.sh
#        - --group_replication_group_seeds='mysqlmaster:6606'
#  mysqlconfigure:
#    image: .
#    environment:
#      - "MYSQL_SLAVE_PASSWORD=root"
#      - "MYSQL_MASTER_PASSWORD=root"
#      - "MYSQL_ROOT_PASSWORD=root"
#      - "MYSQL_REPLICATION_USER=repl"
#      - "MYSQL_REPLICATION_PASSWORD=repl"
#    volumes:
#      - ./mysql_connector.sh:/tmp/mysql_connector.sh
#    command: /bin/bash -x /tmp/mysql_connector.sh
